######################################################################
#
# File name : CPU_compile.do
# Created on: Fri May 06 15:03:16 CEST 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
/mnt/HDD/Softwares/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/work
/mnt/HDD/Softwares/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim

/mnt/HDD/Softwares/intelFPGA/20.1/modelsim_ase/bin/vlib modelsim_lib/msim/xil_defaultlib

/mnt/HDD/Softwares/intelFPGA/20.1/modelsim_ase/bin/vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

/mnt/HDD/Softwares/intelFPGA/20.1/modelsim_ase/bin/vcom -64 -2008 -work xil_defaultlib  \
"../../../../projet_system_info.srcs/sources_1/new/types.vhd" \

/mnt/HDD/Softwares/intelFPGA/20.1/modelsim_ase/bin/vcom -64 -93 -work xil_defaultlib  \
"../../../../projet_system_info.srcs/sources_1/new/memory_manager.vhd" \

/mnt/HDD/Softwares/intelFPGA/20.1/modelsim_ase/bin/vcom -64 -2008 -work xil_defaultlib  \
"../../../../projet_system_info.srcs/sources_1/new/ALU.vhd" \
"../../../../projet_system_info.srcs/sources_1/new/registers.vhd" \
"../../../../projet_system_info.srcs/sources_1/new/decoder.vhd" \
"../../../../projet_system_info.srcs/sources_1/new/write_back.vhd" \
"../../../../projet_system_info.srcs/sources_1/new/ROM.vhd" \
"../../../../projet_system_info.srcs/sources_1/new/branch_manager.vhd" \
"../../../../projet_system_info.srcs/sources_1/new/data_fetch.vhd" \
"../../../../projet_system_info.srcs/sources_1/new/CPU.vhd" \

