######################################################################
#
# File name : CPU_simulate.do
# Created on: Tue May 24 17:38:32 CEST 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L secureip -lib xil_defaultlib xil_defaultlib.CPU

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {CPU_wave.do}

view wave
view structure
view signals

do {CPU.udo}

run 1000ns

quit -force
