######################################################################
#
# File name : CPU_wave.do
# Created on: Tue May 24 17:38:32 CEST 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
