######################################################################
#
# File name : CPU_wave.do
# Created on: Fri May 06 15:03:16 CEST 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
