######################################################################
#
# File name : registers_tb.udo
# Created on: Mon May 02 20:24:20 CEST 2022
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
