#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Mentor Graphics ModelSim Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri May 06 15:03:16 CEST 2022
# SW Build 3367213 on Tue Oct 19 02:47:39 MDT 2021
#
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# usage: simulate.sh
#
# ****************************************************************************
bin_path="/mnt/HDD/Softwares/intelFPGA/20.1/modelsim_ase/bin"
set -Eeuo pipefail
$bin_path/vsim -64 -c -do "do {CPU_simulate.do}" -l simulate.log

